/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 letterA.gltf
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Model(props) {
  const { nodes, materials } = useGLTF('/letterA.gltf');
  return (
    <group
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes['3D_Text_-_A'].geometry}
        material={materials['Light Aroma']}
        position={[-0.04, 0, -0.02]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.5}
      />
    </group>
  );
}

useGLTF.preload('/letterA.gltf');
